#!/bin/bash -eu

DEBS=${DEBS:-/srv/local-apt-repository}
CONFS=${CONFS:-$(dirname $(realpath $0))}

DEBUG=${DEBUG:-0}

dumpvar() {
    declare -p "$1" | sed -r 's/^[^=]*=\(?//; s/\)?$//'
}

pp() {
    echo -n "$1: " >&2
    dumpvar $1 >&2
}

extract_array() {
    local -n ret=$1 s=$2
    eval "ret=($s)"
}

github.expand_conf() {
    local -n ret2=$1
    local -nr rw=$2
    local repos=${rw[1]} pkg=${rw[2]-}
    github.expand_repos repos
    github.expand_pkg pkg repos
    ret2+=([repos]=$repos [pkg]=$pkg)
}

github.expand_repos() {
    local -n ret=$1
    if [[ $ret == */* ]]; then
        return
    fi
    ret=$ret/$ret
}

github.expand_pkg() {
    local -n ret=$1
    local -nr repo=$2
    if [[ $ret == *.deb ]]; then
        return
    fi
    if [[ -z "$ret" ]]; then
        ret=${repo#*/}
    fi
    ret="${ret}_%v_%a.deb"
}

normalize_proto() {
    local -n ret2=$1 lin=$2
    case $ret2 in
        https|http)
            ret2=direct
            ;;
        github)
            ;; # let it be
        *)
            echo unknown protocol: "'$proto'" in "$lin" >&2
            exit 2
            ;;
    esac
}

direct.expand_conf() {
    local -n ret2=$1
    local -nr lin=$3
    ret2+=([url]="$lin")
}

expand_conf() {
    local -n ret=$1
    local -r line="$(echo "$2" | sed 's/ *#.*//')"
    local -ra row=(${line//:/ })
    local proto=${row[0]}
    normalize_proto proto line
    ret=([proto]=$proto)
    $proto.expand_conf ret row line
}

load_conf() {
    local -r path=$CONFS/update-debs-source
    local -n ret=$1

    local line
    local -A entry
    while read -r line; do
        expand_conf entry "$line"
        ret+=("$(dumpvar entry)")
    done < $path
}

direct.fetch() {
    local -n entr=$1
    local -r url="${entr[url]}"
    pushd "$DEBS" >/dev/null
    if (( DEBUG )); then
        echo "$url" >&2
        popd >/dev/null
        return
    fi
    $wget --content-disposition -N "$url"
    popd >/dev/null
}

github.latest_version() {
    local -n ret=$1
    local -r base="$2"
    ret=$($wget --spider -S "$base" 2>&1|sed -r 's|  Location: .*/v?([^/]+)$|\1|p;d')
}

github.url_base() {
    local -n ret=$1
    local -r repos="$2"
    ret="https://github.com/$repos/releases/latest/download"
}

github.format_pkg() {
    local -n ret=$1
    local -r pk=$2 v=$3
    ret=$(echo $pk | sed "s/%a/$arch/; s/%v/$v/")
}

github.url() {
    local -n ret=$1 e=$2
    local -r repos="${e[repos]}"
    local base ver pkg
    github.url_base base $repos
    github.latest_version ver "$base"
    github.format_pkg pkg "${e[pkg]}" $ver
    ret="$base/$pkg"
}


github.fetch() {
    local -nr ent=$1
    local url
    github.url url ent
    local -rA e=([url]="$url")
    direct.fetch e
}

fetch() {
    local -rn cnf=$1
    local -A entry
    local buf
    for buf in "${cnf[@]}"; do
        extract_array entry buf
        ${entry[proto]}.fetch entry &
    done
    wait
}

main() {
    # globals
    local -r arch=$(dpkg --print-architecture)
    local -r wget='wget --no-verbose'
    local -r progname=$(basename $0)

    local -a conf
    load_conf conf
    fetch conf
}

main "$@"
